// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwugjergomzhjqxdaaww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3dWdqZXJnb216aGpxeGRhYXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMjM2NzEsImV4cCI6MjA3NDU5OTY3MX0.qq0_Wac8iuMMHG6ZDrBTWUkYeP_1MjtIsHWjnJiqPl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});